# Check docker/Dockerfile
version: "3.9"
services:
  cameltrack-env:
    container_name: cameltrack-env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: cameltrack-env
    stdin_open: true
    tty: true
    command: bash

    shm_size: 16gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '${GPU}' ]
              capabilities: [ gpu ]
          cpus: '${CPUS:-1.0}'

    volumes:
      - '/tmp:/tmp'
      - '${DATA}:/media/home'
      - '${CODE:-$PWD}:/cameltrack'

  cameltrack-tensorboard:
    container_name: cameltrack-tensorboard
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: cameltrack-env
    stdin_open: true
    tty: true
    command: bash

    shm_size: 16gb

    ports:
      - "56006:6006"
      - "56007:6007"
      - "56008:6008"

    volumes:
      - '${DATA}:/media/home'
