_target_: cameltrack.utils.CAMELTrackLauncher
_recursive_: false
training_enabled: true
checkpoint_path: null # /auto/globalscratch/users/b/s/bstandae/dancetrack/2024-10-30/19-52-02/3/SimFormer/last.ckpt
override_cfg: null
train_cfg:
  use_wandb: ${use_wandb}
  use_rich: ${use_rich}
  evaluate_only: false
  model_selection_criteria: last
  pl_trainer:
    max_epochs: 10
    precision: 32
    gradient_clip_val: 0
    accumulate_grad_batches: 1
    enable_progress_bar: true
    enable_model_summary: false
    profiler: null
    num_sanity_val_steps: 0
    log_every_n_steps: 50
    check_val_every_n_epochs: 1
    val_check_interval: null
    fast_dev_run: false
cameltrack:
  sort:
    _target_: cameltrack.CAMELTrack
    _enabled_: true
    min_hits: 0
    max_wo_hits: 150
    max_gallery_size: 50
    min_init_conf: 0.9
det_filter_cfg:
  min_vis_keypoints: null
  vis_keypoint_threshold: null
  min_bbox_threshold: 0.4
CAMEL:
  transformer_cfg:
    _target_: cameltrack.architecture.Encoder
    emb_dim: 1024
    n_heads: 8
    n_layers: 4
    dim_feedforward: 2048
    dropout: 0.1
    activation_fn: relu
    use_processed_track_tokens: true
    src_key_padding_mask: true
    checkpoint_path: null
    enable_track_det_token: false
    enable_src_norm: true
    enable_src_drop: true
    enable_xavier_init: false
  tokenizers_cfg:
    app_encoder:
      _target_: cameltrack.architecture.TemporalEncoder
      _enabled_: true
      _recursive_: false
      hidden_dim: 512
      output_dim: ${...transformer_cfg.emb_dim}
      n_heads: 8
      n_layers: 4
      dim_feedforward: 1024
      num_registers: 0
      dropout: 0.1
      checkpoint_path: null
      occlusion_threshold: null
      pass_detections: true
      output_strat: cls
      use_pe: true
      use_drop: true
      use_norm: true
      freeze: false
      det_tokenizer:
        _target_: cameltrack.architecture.DetTokenizer
        feats_tokenizers:
        - _target_: cameltrack.architecture.EmbeddingsLinProj
          use_parts: true
    kp_encoder:
      _target_: cameltrack.architecture.TemporalEncoder
      _enabled_: true
      _recursive_: false
      hidden_dim: 128
      output_dim: ${...transformer_cfg.emb_dim}
      n_heads: 8
      n_layers: 4
      dim_feedforward: 256
      num_registers: 0
      dropout: 0.1
      checkpoint_path: null
      occlusion_threshold: null
      pass_detections: true
      output_strat: cls
      use_pe: true
      use_drop: true
      use_norm: true
      freeze: false
      det_tokenizer:
        _target_: cameltrack.architecture.DetTokenizer
        feats_tokenizers:
        - _target_: cameltrack.architecture.KeypointsLinProj
          use_conf: false
    bbox_encoder:
      _target_: cameltrack.architecture.TemporalEncoder
      _enabled_: true
      _recursive_: false
      hidden_dim: 64
      output_dim: ${...transformer_cfg.emb_dim}
      n_heads: 8
      n_layers: 4
      dim_feedforward: 128
      num_registers: 0
      dropout: 0.1
      checkpoint_path: null
      occlusion_threshold: null
      pass_detections: true
      output_strat: cls
      use_pe: true
      use_drop: true
      use_norm: true
      freeze: false
      det_tokenizer:
        _target_: cameltrack.architecture.DetTokenizer
        feats_tokenizers:
        - _target_: cameltrack.architecture.BBoxLinProj
          use_conf: true
  _target_: dd_sort.SimFormer
  merge_token_strat: sum
  sim_strat: norm_euclidean
  assos_strat: hungarian
  use_computed_threshold: false
  sim_threshold: 0.1
  loss_strat: infoNCE
  norm_coords: positive
  tl_margin: 0.2
  contrastive_loss_strat: inter
  train_cfg:
    init_lr: 0.0001
    weight_decay: 0.0001
    alpha_loss: 1.0
  classifier_cfg: null
datamodule:
  batch_transforms:
    train:
      _target_: cameltrack.train.transforms.Compose
      transforms:
      - _target_: cameltrack.train.transforms.AppEmbNoise
        alpha: 0.4
      - _target_: cameltrack.train.transforms.KeypointsShake
        alpha: 0.05
      - _target_: cameltrack.train.transforms.BBoxShake
        alpha: 0.05
  tracklet_transforms:
    train:
      _target_: cameltrack.train.transforms.Compose
      transforms:
      - _target_: cameltrack.train.transforms.MaxNumObs
        max_num_obs: 150
      - _target_: cameltrack.train.transforms.ProbabilisticTransform
        probs:
        - 0.4
        - 0.4
        - 0.1
        transforms:
        - _target_: cameltrack.train.transforms.SwapSporadic
          p_swap: 0.2
          sigma: 50
          method: gaussian
        - _target_: cameltrack.train.transforms.DropoutSporadic
          p_drop: 0.2
          sigma: 50
          method: gaussian
        - _target_: cameltrack.train.transforms.SwapOccluded
          p_swap: 0.5
          min_iou: 0.5
  _target_: cameltrack.train.CAMELDataModule
  sampler: simple
  sampler_args:
    fill_samples: true
  num_videos: null
  num_workers: ${num_cores}
  max_length: 50
  batch_size: 8
  num_samples: 32
  samples_per_video: 100
  train_add_val: true
  dataset_splits:
  - train
  - val
  name: cameltrack-kpr-dancetrack
  path: ${dataset.dataset_path}/states/camel_training_fix_norm
  tracker_states:
    train: ${dataset.dataset_path}/states/kpr/train-my_det-hrnetposetrack18-kpr-ocsort2.pklz
    val: ${dataset.dataset_path}/states/kpr/val-my_det-hrnetposetrack18-kpr-ocsort2.pklz
    test: ${dataset.dataset_path}/states/kpr/test-my_det-hrnetposetrack18-kpr-ocsort2.pklz
  dataset_transforms:
  - add_detections
  - add_last_obs_counter
  - add_occlusions
  - add_dim_image
