# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing CAMELTrack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: 'uv.lock'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: uv sync
    - name: Restore cached models
      id: models-restore
      uses: actions/cache/restore@v4
      with:
        path: pretrained_models
        key: ${{ runner.os }}-models
    - name: Test with tracklab
      run: uv run tracklab dataset.nframes=10
    - name: Save models
      id: models-save
      uses: actions/cache/save@v4
      with:
        path: pretrained_models
        key: ${{ steps.models-restore.outputs.cache-primary-key }}
